### ISSUE TITLE
Check that all matrix data is device-resident during solving

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#431]
After #393 and #395 are finished, update any remaining CUDA wrapper functions to use CUDA matrix types and ensure that all matrix data remains device-resident during solving.

**Acceptance Criteria**
- CUDA Rosenbrock solver integration test continues to pass after updating all CUDA wrapper functions to use CUDA matrix types

**Ideas**
- Functions to update
- [x] `CudaProcessSet::AddForcing()` (fixed by #439 )
- [x] `CudaProcessSet::SubtractJacobianElement()` (fixed by #446 )
- [x] `CudaLuDecomposition::Decompose()` (fixed by #464 )
- [x] `CudaLinearSolver::Solve()` (fixed by #474 )
- [x] `CudaRosenbrock::AlphaMinusJacobian()` (fixed by #452 )
- [x] `CudaRosenbrock::NormalizedErrorDriver()` (fixed by #452 )
